### PR TITLE
Memoize hook return

### PR DESCRIPTION
**Pull request by sdemjanenko**
Avoid returning new arrays/objects when the components of said arrays/objects have not changed. This will help users avoid re-renders in their code.

### CODE REVIEW

**Comment by cgarrovillo** [comment]
+1. Right now the re-renders are super inefficient and unnecessary.

**Comment by matamatanot** [comment]
👍 +1

**Comment by chrisbianca** [comment]
@sdemjanenko thanks for the submission, and apologies for the delay in getting this merged in

**Comment by imjared** [comment]
will this be cut into a new release?

**Comment by chrisbianca** [comment]
This has now been released in https://github.com/CSFrequency/react-firebase-hooks/releases/tag/v3.0.1

**Pull request merged**
