### PR TITLE
Upgrade firebase and update imports to work w/ upstream changes

### PR DESCRIPTION
**Pull request by mdirolf**
Firebase 8.0.0 seems to necessitate changes to how it gets imported:
https://firebase.google.com/support/release-notes/js#version_800_-_october_26_2020

### CODE REVIEW

**Comment by lukaselmer** [comment]
This is very helpful! @chrisbianca please consider merging this, thx :)

**Comment by lukaselmer** [comment]
Until this is is merged and published, I released a version with the fix of @mdirolf on npm.

```json
{
  "dependencies": {
    "@lukaselmer/react-firebase-hooks": "^2.2.1"
  }
}
```

**Comment by chrisbianca** [comment]
@mdirolf thanks for the submission and apologies for the delay in merging this in

**Comment by mdirolf** [comment]
No sweat, thanks for the useful library

**Comment by chrisbianca** [comment]
This has now been released in https://github.com/CSFrequency/react-firebase-hooks/releases/tag/v3.0.1

**Pull request merged**
