### PR TITLE
Firebase 9 Support

### LINKED ISSUE #105: Support for firebase@ext?
Hi, is there any plan to add support to firebase@ext and its new API?

Thanks!

### PR DESCRIPTION
**Pull request by jdpowell1**
Adds support for Firebase 9.

Closes #105 

Firestore and Database hooks are using the compat imports currently, as I'm not familiar with those APIs. In order to get the full tree-shaking improvements of Firebase 9, these compat imports will need to be updated.

### CODE REVIEW

**Comment by lcdss** [comment]
There is something that have to be done to get this PR merged?

**Comment by klutchdev** [comment]
I wanted to check up on this too!
Is there anything I can do to help get a useAuthState hook operational that will work with auth/onAuthStateChanged found in the new modular v9 auth SDK?

**Comment by klutchdev** [comment]
I forked this repo, updated dependencies, replaced 2 webpack packages, and refactored everything needed to support Firebase v9 beta. Obviously these changes will break anything NOT using v9 Beta, so a major update with all those breaking changes wouldn't be a slick move. But, I am more than happy to get something together so we could have a seperate release specifically for v9 that would be available in addition to the current RFH package which is awesome. So far I have all Auth features, storage features, and a couple Firestore features tested and running smooth without any errors or dependency issues. I'm here to help out if this something you all would deem useful!

**Comment by lcdss** [comment]
> I forked this repo, updated dependencies, replaced 2 webpack packages, and refactored everything needed to support Firebase v9 beta. Obviously these changes will break anything NOT using v9 Beta, so a major update with all those breaking changes wouldn't be a slick move. But, I am more than happy to get something together so we could have a seperate release specifically for v9 that would be available in addition to the current RFH package which is awesome. So far I have all Auth features, storage features, and a couple Firestore features tested and running smooth without any errors or dependency issues. I'm here to help out if this something you all would deem useful!

Did you remove the compat to be complete modular? From firebase docs:
> Compat libraries have little to no size or performance advantages over their version 8 counterparts.

**Comment by klutchdev** [comment]
I did

**Comment by leoortizz** [comment]
@chrisbianca is there any plans on merging this PR?

**Comment by TheSwordBreaker** [comment]
```
node_modules/react-firebase-hooks/auth/dist/auth/useAuthState.d.ts:3:58 - error TS2694: Namespace '"D:/KUNAL/User/React/superchat/node_modules/firebase/app/dist/app/index"' has no exported member 'User'.

3 export declare type AuthStateHook = LoadingHook<firebase.User | null, firebase.auth.Error>;
```


Can Anyone file me

**Comment by justdvl** [comment]
Seems I will have to remove react-firebase-hooks from my project :(

**Comment by Lactem** [comment]
Would love to see this get merged!

**Comment by Skia69** [comment]
You guys might wanna check this one out https://github.com/FirebaseExtended/reactfire
It has been updated to v4 about a month ago which supports firebase v9

**Comment by melWiss** [comment]
aaaaaaaaaaaaanything new about merging this PR?

**Comment by fabienrohrer** [comment]
Please merge this PR 👍

**Comment by andipaetzold** [comment]
👋  All my projects are also stuck on firebase 8, and this PR doesn't do a full migration to firebase 9 but still uses the compatibility imports.

Therefore, I tried to do a full migration of the whole package and opened a separate [PR](https://github.com/CSFrequency/react-firebase-hooks/pull/174) converts all components and the documentation. That PR is temporarily deployed as [`react-firebase9-hooks`](https://www.npmjs.com/package/react-firebase9-hooks) to allow easy testing and migration of projects to the latest firebase version without depending on `react-firebase-hook` to release an update.

More details in the PR: https://github.com/CSFrequency/react-firebase-hooks/pull/174

**Comment by Skia69** [comment]
> 👋 All my projects are also stuck on firebase 8, and this PR doesn't do a full migration to firebase 9 but still uses the compatibility imports.
> 
> Therefore, I tried to do a full migration of the whole package and opened a separate [PR](https://github.com/CSFrequency/react-firebase-hooks/pull/174) converts all components and the documentation. That PR is temporarily deployed as [`react-firebase9-hooks`](https://www.npmjs.com/package/react-firebase9-hooks) to allow easy testing and migration of projects to the latest firebase version without depending on `react-firebase-hook` to release an update.
> 
> More details in the PR: #174

Not all heroes wear capes.

**Comment by theonlydaleking** [comment]
We should actually get him a cape tho

**Comment by jdpowell1** [comment]
Closed in favour of #174 which doesn't use compat imports. Nice job @andipaetzold

**Pull request closed without merging**
