### PR TITLE
use finally to remove duplication

### PR DESCRIPTION
**Pull request by mikeattara**

### CODE REVIEW

**Comment by mikeattara** [comment]
If that is okay, I can go ahead and make the changes in other parts in this pull request. Thanks

**Comment by chrisbianca** [comment]
@mikeattara Thanks for the submission. This would be a nice bit of tidy up, so if you're ok to push this through the rest of the code base then I would be very happy to get it merged in.

**Comment by mikeattara** [comment]
@chrisbianca, I have done that.

**Comment by mikeattara** [comment]
@chrisbianca any feedback?

**Comment by chrisbianca** [comment]
@mikeattara sorry for the delay, this has now been merged

**Pull request merged**
